### ISSUE TITLE
About the DIOR dataset

### ISSUE THREAD

**Issue by xiaofeng-c** [RSer-XDU/G-FSDet#1]
Thank you for your work, and i'm insterested in your work, i would like to know how to split the DIOR dataset or could you please release the splited DIOR dataset, thanks.

**Comment by RSer-XDU** [comment]
@xiaofeng-c Thank You for your interest. 

  We provide the few-shot annotation for the fine-tuning stage in the dir: G-FSDet/data/few_shot_ann/dior/.
  As for the base dataset for base training, we directly use the trainval.txt provided with the DIOR dataset.
  Please look at our paper to see the detailed base/novel classes splits in Table 1 of our paper [1]. 

[1] Zhang T, Zhang X, Zhu P, et al. Generalized few-shot object detection in remote sensing images[J]. ISPRS Journal of Photogrammetry and Remote Sensing, 2023, 195: 353-364.

**Comment by xiaofeng-c** [comment]
OK，many thanks.
