### ISSUE TITLE
DIOR fewshot split

### ISSUE THREAD

**Issue by Tarazed** [RSer-XDU/G-FSDet#2]
Could you please provide the random seed when you split DIOR? I want to evaluate the model on 30-shot so I need to obtain the 30-shot annotations for each class.

**Comment by RSer-XDU** [comment]
Appreciate your interest.
We use the random seed 0 for the selection of few-shot annotation and update the few-shot annotation with 30 shots in the DIOR dataset.

**Comment by Tarazed** [comment]
Thanks!

**Comment by YongZh958** [comment]
你好，我参考https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/prepare_voc_few_shot.py这个脚本进行少样本划分，但是seed为0时，划分结果与项目中提供的不一样，请问这是为什么呢？
