### ISSUE TITLE
NWPU VHR-10v2

### ISSUE THREAD

**Issue by Tarazed** [RSer-XDU/G-FSDet#4]
Could you please tell me where to download the NWPU VHR-10v2? I can only find NWPU VHR-10 which contains 800 images rather than 1172 images. And it would be appreciated if you could provide the few-shot split files. Thank you!

**Comment by lian704** [comment]
Hello, do you know how to use DisKDBBoxHead and DisCosSimBBoxHead?

**Comment by Tarazed** [comment]
> Hello, do you know how to use DisKDBBoxHead and DisCosSimBBoxHead?

You can modify `bbox_head` in fsdetview_r50_c4.py

**Comment by lian704** [comment]
Thank you for your reply. I have tried modifying bbox_ head before_ Head, but it was not successful. Can you show me how you modified it? And perhaps this is the data you need.
https://drive.google.com/file/d/15xd4TASVAC2irRf02GA4LqYFbH7QITR-/view

**Comment by Tarazed** [comment]
> Thank you for your reply. I have tried modifying bbox_ head before, but it was not successful. Can you show me how you modified it? And perhaps this is the data you need. https://drive.google.com/file/d/15xd4TASVAC2irRf02GA4LqYFbH7QITR-/view

Thanks for providing the dataset! Sorry that I have not tried the code with DisKDBBoxHead or DisCosSimBBoxHead, but the code is based on mmdetection and the config change should work. Could you please tell me more about your failure information?

**Comment by Tarazed** [comment]
> For DisKDBBoxHead, I tried to modify type and init_cfg in the bbox_head, and added base_cpt and dis_loss, but it seems that the results have not changed much, loss_kd has always been 0. For DisCosSimBBoxHead, I only added dis_loss, but the result will actually decrease. This is my code： ![image](https://user-images.githubusercontent.com/130283178/233075697-44c24e09-5685-4737-995f-e0a929210dd4.png)

Well, sorry that I can't tell you what is wrong then. We may have to wait for the author's reply.

**Comment by RSer-XDU** [comment]
@Tarazed @lian704 Thank You for your concern, the relevant files are updated.

**Comment by Tarazed** [comment]
Thank you.
