### ISSUE TITLE
作者大大是否能提供NWPU VHR-10.v2原数据集

### ISSUE THREAD

**Issue by guanlaoshi** [RSer-XDU/G-FSDet#5]
感谢作者大大在本领域做出的贡献。我也是才接触小样本这个领域，但是在NWPU VHR-10.v2数据集收集上犯难了。我在原文中找到数据集的链接，但是失效了。同时我在网上也找到了一个https://drive.google.com/file/d/15xd4TASVAC2irRf02GA4LqYFbH7QITR-/view
，但是标签大部分是错误的。希望大大可以有空的时候发一个链接或者邮箱给我，谢谢
我的邮箱793763912@qq.com

**Comment by yomik-js** [comment]
> 

您好，请问您收到这个数据集了吗？方便的话可以麻烦您分享一下吗？这是我的邮箱 214557065@qq.com

**Comment by guanlaoshi** [comment]
> 

好的，不过目前还未收到，作者可能最近很忙

**Comment by guanlaoshi** [comment]
> > 
> 
> 您好，请问您收到这个数据集了吗？方便的话可以麻烦您分享一下吗？这是我的邮箱 [214557065@qq.com](mailto:214557065@qq.com)

可能最近作者大大比较慢，目前没有收到数据集，后面如果有的话，发你一份

**Comment by RSer-XDU** [comment]
@guanlaoshi @yomik-js 
可以看下这个链接，感谢关注
https://drive.google.com/file/d/1ufoSMK_J0cHth-Or5bEmbAIaH8SxzsXo/view?usp=sharing

**Comment by guanlaoshi** [comment]
> @guanlaoshi @yomik-js 可以看下这个链接，感谢关注 https://drive.google.com/file/d/1ufoSMK_J0cHth-Or5bEmbAIaH8SxzsXo/view?usp=sharing

谢谢作者大大
